[workspace]
resolver = "2"
members = ["zk-logic", "zk-rand/host"]


[profile.release]
debug = 1
lto = true

[workspace.package]
name = "zk-random"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
