[package]
name = "zk-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version="1", default-features=false, features=["derive", "alloc"]}
sha2 = {version="0.10.8", default-features=false}
num-bigint={version="0.4.6", default-features=false}